config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                  Controller#Action
# sessions_new GET    /sessions/new(.:format)      sessions#new
#         root GET    /                            pages#home
#        users POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#    edit_user GET    /users/:id/edit(.:format)    users#edit
#         user GET    /users/:id(.:format)         users#show
#              PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#     whistles POST   /whistles(.:format)          whistles#create
#  new_whistle GET    /whistles/new(.:format)      whistles#new
# edit_whistle GET    /whistles/:id/edit(.:format) whistles#edit
#      whistle GET    /whistles/:id(.:format)      whistles#show
#              PATCH  /whistles/:id(.:format)      whistles#update
#              PUT    /whistles/:id(.:format)      whistles#update
#        login GET    /login(.:format)             session#new
#              POST   /login(.:format)             session#create
#              DELETE /login(.:format)             session#destroy
#

Rails.application.routes.draw do
  root :to => 'pages#home'

  get '/users/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id/relationships' => 'users#relationships', as: :create_relationship
  delete '/users/:id/destroy_relationship' => 'users#destroy_relationship', as: :destroy_relationship
  resources :users, :only => [:new, :create, :show, :update]
  resources :whistles

  resources :whistles do
    put :star, on: :member
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :whistles
  resources :tags, only: [:index, :show]
end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Relationship < ActiveRecord::Base
  belongs_to :follower, :class_name => 'User', :foreign_key => 'follower_id'
  belongs_to :followed, :class_name => 'User', :foreign_key => 'followed_id'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/star_whistle.rb
# == Schema Information
#
# Table name: star_whistles
#
#  id         :integer          not null, primary key
#  whistle_id :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class StarWhistle < ActiveRecord::Base
  belongs_to :whistle
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  username        :text
#  name            :text
#  password_digest :string
#  profile_pic     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean
#

class User < ActiveRecord::Base
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :whistles, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :star_whistles, dependent: :destroy
  has_many :stars, through: :star_whistles, source: :whistle

  def self.search(search)
    where("name ILIKE ? OR username ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/models/whistle.rb
# == Schema Information
#
# Table name: whistles
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post       :text
#  star       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Whistle < ActiveRecord::Base

  belongs_to :user

  acts_as_taggable_on :tags

  has_many :star_whistles, dependent: :destroy
  has_many :stared_by, through: :star_whistles, source: :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by :id => session[:user_id]
    end
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_user
    redirect_to root_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless (@current_user.present? && @current_user.admin?)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to whistles_path
    else
      flash[:message] = 'Invalid email or password'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @whistles = Whistle.tagged_with(@tag.name)
    @user = @whistles.each do |f|
      f.user
    end
    render :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to whistles_path # Sign up was successful
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
    @relationship = Relationship.all
  end

  def relationships
    @user = User.find params[:id]

    Relationship.create :follower_id => @current_user.id, :followed_id => @user.id
    redirect_to user_path(@user)
  end

  def destroy_relationship
    @user = User.find params[:id]
    r = Relationship.where :follower_id => @current_user.id, :followed_id => @user.id
    r.first.destroy
    redirect_to user_path(@user)
  end

  def edit
    @user = @current_user
    # @user = User.find params[:id]
  end

  def update
    # @user = @current_user
    @user = User.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @user.profile_pic = req["public_id"]
    end
    @user.update_attributes user_params
    @user.save
    if @user.update_attributes user_params
      flash[:message] = 'Profile successfully updated'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :name, :password, :password_confirmation, :profile_pic)
  end
end

app/controllers/whistles_controller.rb
class WhistlesController < ApplicationController

  def index
    @whistles = Whistle.all
  end

  def new
    @whistle = Whistle.new
  end

  def create
    # @whistle = Whistle.new whistle_params
    @whistle = @current_user.whistles.new whistle_params # creates association to current user
    if @whistle.save
      redirect_to whistles_path
    else
      render :new
    end
  end

  def show
    @whistle = Whistle.find params[:id]
  end

  def destroy
    whistle = Whistle.find params[:id]

    ## Stops other users from deleting your post
    redirect_to whistle if whistle.user_id != @current_user.id

    whistle.destroy
    redirect_to whistles_path
  end

  def star
    @whistle = Whistle.find params[:id]
    type = params[:type]
    if type == "star"
      @current_user.stars << @whistle
      redirect_to :back
    elsif type == "unstar"
      @current_user.stars.destroy(@whistle)
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private
  def whistle_params
    params.require(:whistle).permit(:user_id, :post, :posted_at, :star, :create_at, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twettir</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="nav_outer">
    <nav>
      <% if @current_user.present? %>
      <div class="navigation">

        <%= link_to "Home", whistles_path, :class => 'nav' %>
        <%= link_to "Profile", user_path(@current_user), :class => 'nav' %>

      </div>

      <div class="twettir_icon_nav">
        <h3 class="twettir_icon">ஐ</h3>
      </div>

      <div class="nav_right">

        <%= link_to "Logout #{ @current_user.username }", login_path, :method => 'delete', :class => 'nav' %>

        <%= link_to 'Whistle', "#openModal", :class => "createWhistleButton" %>

        <div id="openModal" class="modalDialog">
          <div><a href="#close" title="Close" class="close">x</a>
            <div class="spacefiller">Compose new Whistle</div>
            <div class="allPosts createPost">
            <%= form_for Whistle.new do |f| %>
              <p>
                <%= image_tag @current_user.profile_pic, :class => 'dp_thumb' %>
                <%= f.text_area :post, :placeholder => "What's happening?", :size => 60, :maxlength => 140, :class => 'postWhistle' %>
              </p>
              <p>
                <%= f.text_field :tag_list, :placeholder => 'Insert #tags here', :class => 'postTag' %>
              </p>
            <div class="submitButton">
            <%= f.submit 'Whistle', :class => 'submitButtonWhistle' %>
            </div>
          </div>
        </div>
      </div>
        <% end %>


      <% else %>
      <div class="navigation">
        <%= link_to 'ஐ', root_path, :class => 'nav twettir_icon' %>
      </div>
      <div class="nav_right">
        <%= link_to 'Sign up', new_user_path, :class => 'createWhistleButton' %>
        <%= link_to 'Sign in', "#openModal", :class => "createWhistleButton" %>
      </div>
        <div id="openModal" class="modalDialog">
          <div><a href="#close" title="Close" class="close">x</a>
            <div class="spacefiller">Sign in to Twettir</div>
            <div class="signInPost">

              <%= form_tag login_path do %>
              <p>
                <%= email_field_tag :email, nil, :placeholder => 'Email', :class => 'signInForm' %>
              </p>
              <p>
                <%= password_field_tag :password, nil, :placeholder => 'Password', :class => 'signInForm' %>
              </p>

                <%= submit_tag 'Log in', :class => 'signUpFormButton' %>
              <% end %>
            </div>
          </div>
        </div>

      <% end %>
    </nav>
  </div>
<div class="spacer"></div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<div class="signUp">
  <div class="signUpBoard signUpBoardHome">
    <h2 class="signUpFormTitle">Twettir.</h2>
    <div class="homePageBlurb">
      <h3>
        What's Happening?
      </h3>
      <% if session[:user_id].present?%>
        <%= @current_user.username%>!
        <p>
          You are logged in with user id : <%= session[:user_id] %>
        </p>
      <% else %>
        <p>
          <em>One programmers attempt to rebuild twitter from scratch.</em>
        </p>
        <p>
          <%= link_to 'Sign up', new_user_path %> | <%= link_to 'Sign in', '#openModal' %> to get started.
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/session/new.html.erb
<div class="signUp">
  <div class="signUpBoard">
    <h2 class='signUpFormTitle'>Sign in to Twettir</h2>

    <% if flash[:message].present? %>
      <p><%= flash[:message] %></p>
    <% end %>

    <%= form_tag login_path do %>
    <p>
      <%= email_field_tag :email, nil, :placeholder => 'Email', :class => "signUpForm" %>
    </p>

    <p>
      <%= password_field_tag :password, nil, :placeholder => 'Password', :class => "signUpForm" %>
    </p>

    <%= submit_tag 'Log in', :class => 'signUpFormButton' %>

    <% end %>
  </div>
</div>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<div class="signUp">
  <div class="signUpBoard">
    <h2 class='signUpFormTitle'><%= @tag.name %></h2>

    <div class="showTagPosts"><%= render @whistles %></div>

  </div>
</div>

app/views/users/edit.html.erb
<div class="signUp">
  <div class="signUpBoard">
    <h2 class='signUpFormTitle'>Edit profile</h2>

<div class="error">
  <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
  <% end %>
</div>

<%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <p>
    <%= f.email_field :email, :required => true, :placeholder => 'Email', :class => "signUpForm" %>
  </p>

  <p>
    <%= f.text_field :username, :required => true, :placeholder => 'Username', :class => "signUpForm" %>
  </p>

  <p>
    <%= f.text_field :name, :required => true, :placeholder => 'Name', :class => "signUpForm" %>
  </p>

  <p>
    <%= f.password_field :password, :placeholder => 'Password', :class => "signUpForm" %>
  </p>

  <p>
    <%= f.password_field :password_confirmation, :placeholder => 'Confirm Password', :class => "signUpForm" %>
  </p>

  <p>
    <%= f.cl_image_upload :profile_pic, :placeholder => 'Profile picture URL', :class => "signUpForm"  %>
  </p>

<%= f.submit 'Save changes', :class => 'signUpFormButton' %>

<% end %>

app/views/users/new.html.erb
<div class="signUp">
  <div class="signUpBoard">
    <h2 class="signUpFormTitle">Join Twettir today.</h2>

    <% if @user.errors.any? %>
      <ol>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ol>
    <% end %>
    <%= form_for @user do |f| %>
      <p>
        <%= f.email_field :email, :required => true, :placeholder => 'Email', :class => "signUpForm" %>
      </p>

      <p>
        <%= f.text_field :username, :required => true, :placeholder => 'Username', :class => "signUpForm" %>
      </p>

      <p>
        <%= f.text_field :name, :required => true, :placeholder => 'Name', :class => "signUpForm" %>
      </p>

      <p>
        <%= f.password_field :password, :required => true, :placeholder => 'Password', :class => "signUpForm" %>
      </p>

      <p>
        <%= f.password_field :password_confirmation, :required => true, :placeholder => 'Confirm Password', :class => "signUpForm" %>
      </p>

    <%= f.submit 'Sign up', :class => 'signUpFormButton' %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="profileHeader"></div>
<div class="profileNavBar"></div>
<div class="headerSpacer"></div>

<div class="profileInfo">
  <div class="select_nav_profile"></div>
  <ul>
    <li><%= cl_image_tag @user.profile_pic, :class => 'profilePic' %></li>
    <li><h3><%= @user.name %></h3></li>
    <li class="profileUsername">@<%= @user.username %></li>
    <li>E-mail: <%= @user.email %></li>
  </ul>

</div>
<br>

<div class="profileNavContent">
  <a href="#">WHISTLES <span><%= @user.whistles.count %></span></a>
  <a href="#openModaltwo">FOLLOWING<span><%= @relationship.where(:follower_id => @user.id).count %></span></a>
  <a href="#openModalthree">FOLLOWERS<span><%= @relationship.where(:followed_id => @user.id).count %></span></a>
  <a class="starSpan" href="#openModalfour">STARS<span><%= @user.stars.count %></span></a>
</div>

<% if @user.id == @current_user.id %>
<div class="editProfile"><%= link_to 'Edit profile', edit_user_path(@user) %></div>
<% else %>
 <% found = false %>
  <% @relationship.each do |r| %>
    <% if r.follower_id == @current_user.id && r.followed_id == @user.id %>
      <% found = true %>
    <% else %>
      <% found = false %>
    <% end %>
  <% end %>
  <% if found ==  true %>
    <div class=" editProfile">
      <%= link_to "Following", destroy_relationship_path(@user.id), :method => 'delete' %>
    </div>
  <% else %>
    <div class="editProfile">
      <%= link_to "Follow", create_relationship_path(@user.id) %>
    </div>
  <% end %>
<% end %>

<div class="allPosts profilePostPos">
  <% @user.whistles.reverse.each do |whistle| %>
  <div class="allPostsSeg">
    <div class="aside_pp">
      <%= cl_image_tag whistle.user.profile_pic, :class => 'pp_thumb' %>
    </div>
    <div class="allPostNameHeader">
      <div class="allPostName">
        <%= link_to whistle.user.name, :class => 'allPostName' %>
      </div>
      <div class="usernameDate">
        @<%= link_to whistle.user.username %>
        - <%= link_to whistle.created_at.localtime.strftime("%b %d - %I:%M %p") %>
      </div>
      <br>
        <%= link_to whistle.post, whistle %>
      <div class="postButtonLinkBar">

        <% if @current_user %>
          <% if whistle.stared_by.first == nil || whistle.stared_by.first.id != @current_user.id  %>
          <div class="starColor">
            <%= link_to "☆ #{ whistle.stared_by.count }", star_whistle_path(whistle, type: "star"), method: :put, :class => "starColor" %>
          </div>
          <% elsif whistle.stared_by.first.id == @current_user.id %>
          <div class="unstarColor">
            <%= link_to "★ #{ whistle.stared_by.count }", star_whistle_path(whistle, type: "unstar"), method: :put, :class => "unstarColor" %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div id="openModaltwo" class="modalDialog">
  <div><a href="#close" title="Close" class="close">x</a>
    <div class="spacefiller">Following</div>
    <div class="signInPost">

        <% @user.following.each do |n| %>
        <p>
          <%= link_to "#{n.username}", user_path(n) %>
        </p>
        <% end %>
    </div>
  </div>
</div>

<div id="openModalthree" class="modalDialog">
  <div><a href="#close" title="Close" class="close">x</a>
    <div class="spacefiller">Followers</div>
    <div class="signInPost">
      <p>
      <% @relationship.where(:followed_id => @user.id).each do |n| %>
      </p>
        <%= link_to "#{User.find(n.follower_id).username}", user_path(n.follower_id) %>
      <% end %>
    </div>
  </div>
</div>

<div id="openModalfour" class="modalDialog">
  <div><a href="#close" title="Close" class="close">x</a>
    <div class="spacefiller">Followers</div>
    <div class="signInPost">
      <p>
        <% @user.star_whistles.each do |s| %>
      </p>
        <%= link_to "#{Whistle.find(s.whistle_id).post}", whistle_path(s.whistle_id) %>
      <% end %>
    </div>
  </div>
</div>

app/views/whistles/_form.html.erb
<%= form_for whistle do |f| %>
  <%= f.text_field :tag_list %>
  <%= f.submit %>
<% end %>

app/views/whistles/_whistle.html.erb
<h2><%= link_to whistle.post, whistle_path(whistle) %></h2>

app/views/whistles/index.html.erb
<div class="select_nav_home"></div>
<div class="profileSmallHome">
  <%= cl_image_tag @current_user.profile_pic, :class => 'pp_dash' %>
  <div class="dashHeaderImg"></div>
  <div class="profileDashInfo">
    <h3><%= link_to @current_user.name, user_path(@current_user), :class => 'profileDashName' %></h3>
    <%= link_to "@#{@current_user.username}", user_path(@current_user), :class => 'profileDashUsername' %>
  </div>
  <div class="profileDashContent">
  <%= link_to 'WHISTLES', user_path(@current_user) %><span><%= @current_user.whistles.count %></span>
  <%= link_to 'FOLLOWING', user_path(@current_user) %><span><%= Relationship.where(:follower_id => @current_user.id).count %></span>
  <%= link_to 'FOLLOWERS', user_path(@current_user) %><span><%= Relationship.where(:followed_id => @current_user.id).count %></span>
  </div>
</div>

<div class="allPosts allPostsHomePos">
  <% @whistles.reverse.each do |whistle| %>
  <div class="allPostsSeg">
    <div class="aside_pp">
      <%= link_to cl_image_tag(whistle.user.profile_pic), user_path(whistle.user), :class => 'pp_thumb' %>
    </div>
    <div class="allPostNameHeader">
      <div class="allPostName">
        <%= link_to whistle.user.name, user_path(whistle.user) %>
      </div>
      <div class="usernameDate">
        @<%= link_to whistle.user.username, user_path(whistle.user) %>
        - <%= link_to whistle.created_at.localtime.strftime("%b %d - %I:%M %p") %>
      </div>
      <br>
        <%= link_to whistle.post, whistle %>
      <div class="postButtonLinkBar">
        <% if @current_user %>
          <% if whistle.stared_by.first == nil || whistle.stared_by.first.id != @current_user.id %>
          <div class="starColor">
            <%= link_to "☆ #{ whistle.stared_by.count }", star_whistle_path(whistle, type: "star"), method: :put, :class => "starColor" %>
          </div>
          <% elsif whistle.stared_by.first.id == @current_user.id %>
          <div class="unstarColor">
            <%= link_to "★ #{ whistle.stared_by.count }", star_whistle_path(whistle, type: "unstar"), method: :put, :class => "unstarColor" %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/whistles/new.html.erb
<div class="allPosts createPost">

<%= form_for @whistle do |f| %>

  <p>
    <%= cl_image_tag @current_user.profile_pic, :class => 'dp_thumb' %>
    <%= f.text_area :post, :placeholder => "What's happening?", :size => 60, :maxlength => 140, :class => 'postWhistle' %>
  </p>

  <p>
    <%= f.text_field :tag_list, :placeholder => 'Insert #tags here', :class => 'postTag' %>
  </p>

  <div class="submitButton">
    <%= f.submit 'Whistle', :class => 'submitButtonWhistle' %>
  </div>
</div>
<% end %>

app/views/whistles/show.html.erb
<div class="profileSmallHome">
  <div class="hashTagShow">
    <h3>Hashtags: <h3>
    <div class="tag_show"><%= render @whistle.tags %></div>
  </div>
</div>

<div class="allPosts allPostsHomePos">
  <div class="allPostsSeg">
    <ul>
      <li>
        <div class="aside_pp">
          <%= link_to cl_image_tag(@whistle.user.profile_pic), user_path(@whistle.user), :class => 'pp_thumb' %>
        </div>
        <div class="allPostNameHeader">
          <div class="allPostName">
            <%= link_to @whistle.user.name, :class => 'allPostName' %>
          </div>
          <div class="usernameDate">
            @<%= link_to @whistle.user.username %>
            - <%= link_to @whistle.created_at.localtime.strftime("%b %d - %I:%M %p") %>
          </div>
          <br>
            <%= link_to @whistle.post, @whistle %>
          <div class="postButtonLinkBar">
            <% if @current_user %>
              <% if @whistle.stared_by.first == nil || @whistle.stared_by.first.id != @current_user.id  %>
                <div class="starColor">
                  <%= link_to "☆ #{ @whistle.stared_by.count }", star_whistle_path(@whistle, type: "star"), method: :put, :class => "starColor" %>
                </div>
                <% elsif @whistle.stared_by.first.id == @current_user.id %>
                <div class="unstarColor">
                  <%= link_to "★ #{ @whistle.stared_by.count }", star_whistle_path(@whistle, type: "unstar"), method: :put, :class => "unstarColor" %>
                </div>
                  <% end %>
                <% end %>
                <% if @current_user.admin? || @current_user.id == @whistle.user.id %>
              | <%= link_to 'Delete Whistle', @user, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
              <% end %>
          </div>
        </div>

      </li>
    </ul>
  </div>
</div>